#!/usr/bin/env zsh
set -euo pipefail

function getNormalUrlFromSshUrl() {
  local input=${1:4}
  local formattedInput=`sd 'github\.com.*:' 'github.com/' <<< $input | sd '.git$' ''`
  printf "https://$formattedInput"
}

local remoteUrl=`git config --get remote.origin.url`

if [[ -z "$remoteUrl" ]]
  then exit 1
fi

if [[ "$remoteUrl" =~ "^http[s]?:\/{2}" ]]
  then printf $remoteUrl
  else getNormalUrlFromSshUrl $remoteUrl
fi
