#!/usr/bin/env zsh
set -o errexit
set -o pipefail

if [[ -z "$TMUX" ]]; then
  print "This script must be run inside tmux"
  exit 1
fi

zparseopts -D -E -F -- \
  -clear=clear \
  -id:=winId \
  || return 1

local rename=$1

local targetWin
if [[ -n "$winId" ]]
  then targetWin="-t ${winId[2]}"
  else targetWin=""
fi

local action
if [[ -n "$clear" ]]; then
  action="clear"
  tmux rename-window zsh
else
  action="alert"
  if [[ -n "$rename" ]]
    then tmux rename-window "$rename"
  fi
fi

tmux ${action}1 $targetWin \; ${action}2 $targetWin
