#!/usr/bin/env zsh
set -eo pipefail

if [[ -z "$TMUX" ]]; then
  print "This script must be run inside tmux"
  exit 1
fi

zparseopts -D -E -F -- \
  -clear=clear \
  -id:=winId \
  || return 1

local rename=$*

local targetWin
[[ -n "$winId" ]] && targetWin="-t ${winId[1]}"

local action
if [[ -n "$clear" ]]
  then action="clear"
  else action="highlight"
fi

if [[ -n "$rename" && -z "$clear" ]]
  then tmux rename-window "$rename"
fi

if [[ -n "$clear" ]]
  then tmux set automatic-rename
fi

tmux $action $targetWin
