#!/usr/bin/env zsh
set -eo pipefail

if [[ -z "$TMUX" ]]; then
  print "This script must be run inside tmux"
  exit 1
fi

zparseopts -D -E -F -- \
  t:=target \
  -clear=clear \
  || return 1

# these are copied from `clear-highlight` and `highlight` aliases defined in tmux.conf
local action
if [[ -n "$clear" ]]
  then action="set $target window-status-style fg='colour6',bg='#242933'"
  else action="set $target window-status-style fg='colour3',bg='#242933'"
fi

local cmd="tmux $action"

local rename=$*
if [[ -n "$rename" && -z "$clear" ]]
  then cmd+="\; rename-window '$rename'"
fi

if [[ -n "$clear" ]]
  then cmd+="\; set automatic-rename"
fi

eval $cmd
