#!/usr/bin/env zsh
set -eo pipefail

# phase is started | ended
zparseopts -D -E -F -- \
  p:=phaseArg \
  t:=timeArg \
  || return 1

local phase=${phaseArg[2]}
local inputTime=${timeArg[2]}
local message=$*

if [[ -z "$inputTime" ]]
  then printf "time must be specified"; exit 1
fi

if [[ "$phase" != "started" && "$phase" != "ended" ]]
  then printf "phase must be 'started' or 'ended'"; exit 1
fi

TIME=`date +%H:%M:%S`
YEAR=`date +%Y`
MONTH=`date +%b`
THIS_MONTH_FOLDER=pomodoro/$YEAR/$MONTH

function appendPomodoroInfoToLog() {
  # second message decoration
  log_to_zsb "$message $phase at $TIME" $THIS_MONTH_FOLDER
}

if [[ "$phase" = "started" ]]; then
  log_to_zsb ' ' $THIS_MONTH_FOLDER
fi

appendPomodoroInfoToLog

if [[ "$phase" = "ended" ]]; then
  alert "Pomodoro for $inputTime ended" &

  local soundFile=~/.zsh-spell-book/src/media/sounds/xylofon.wav
  [[ -f $soundFile ]] && zsb_play $soundFile &
fi


exit 0
