#!/usr/bin/env zsh


function makeCursorVisible() {
  tput cnorm
}

function makeCursorInvisible() {
  tput civis
}

trap makeCursorVisible EXIT

function spinner() {
  local LC_CTYPE=C

  local pid=$1 # Process Id of the previous running command
  shift 1
  local spin='⣾⣽⣻⢿⡿⣟⣯⣷'
  local charwidth=3

  local msg="\e[38;5;8m# ${@}\033[0m"

  makeCursorInvisible

  local i=0
  while kill -0 $pid 2>/dev/null; do
    local i=$(((i + $charwidth) % ${#spin}))
    printf "\r${spin:$i:$charwidth} ${msg}"

    sleep .1
  done
  print "\rDone ${msg}"

  makeCursorVisible

  wait $pid # capture exit code
  return $?
}

("$@") &

spinner $! "$@"
