#!/bin/bash

declare msg="\e[38;5;8m${@}\033[0m"
declare inputCommandCancelled=true
declare spinnerPid
declare inputCommandExitCode

function makeCursorVisible() {
  tput cnorm
}

function makeCursorInvisible() {
  tput civis
}

function killSpinner() {
  kill $spinnerPid
  wait $! 2>/dev/null
}

function printEndMessage() {
  "$inputCommandCancelled" && printf "\r! ${msg}\n" && \
    return 0

  (( $inputCommandExitCode )) && \
    printf "\r\e[38;5;1m✘\033[0m ${msg}\n" && \
    return 0

  printf "\r\e[38;5;2m✔\033[0m ${msg}\n"
}

function shutdown() {
  killSpinner
  printEndMessage
  makeCursorVisible
}

trap shutdown EXIT

function spinner() {
  local spinnerChars=(⣾ ⣽ ⣻ ⢿ ⡿ ⣟ ⣯ ⣷)
  local spinLenMinusOne="$(( ${#spinnerChars[@]} - 1))"

  local i=0
  while true; do
    printf "\r${spinnerChars[$i]}"
    sleep .1

    [[ "$i" = "$spinLenMinusOne" ]] && i=0 || : $((i++))
  done
}

("$@") &
declare inputCommandPid=$!

makeCursorInvisible
printf "  ${msg}"

spinner &
spinnerPid=$!

wait $inputCommandPid
inputCommandExitCode=$?
inputCommandCancelled=false

exit $inputCommandExitCode
