#!/usr/bin/env zsh
set -euo pipefail

# (tightly coupled with tmux config, ripgrep, and nvim)
# for tmux conf, see https://github.com/EdgardoArriagada/dotFiles/blob/main/tmux/home/.tmux.conf

local filename=${*%%§*}

if [[ ! -f $filename ]]
  then exit 1
fi

function loadFile() {
  # cargo
  export PATH=$PATH:~/.cargo/bin
  # fnm
  eval "$(fnm env --use-on-cd)"

  case $# in
    1) nvim $1 ;;
    2) nvim $1 +${2} -c 'normal zz' ;;
  esac
}

local cursorLine=${*##*§}

if [[ -f "$cursorLine" ]]
  then loadFile $filename; exit 0
fi

# get number out of first number until ':' in a line using param expansion
local lineNumber=${cursorLine%%:*}

# check if number is valid
[[ $lineNumber != <-> ]] && exit 1

loadFile $filename $lineNumber

exit 0
