#!/usr/bin/env zsh
set -o errexit
set -o pipefail

source ~/temp/links.zsh

declare urlList=`print -l ${(@k)ZSB_CHARM_LINKS_DICTIONARY}`
declare selection

if (( $ZSB_MACOS ))
  then selection=`choose ${(z)commonChooseGuiProps} <<< $urlList`
  else selection=`rofi ${(z)commonRofiProps} -i -p 'Open link' <<< $urlList`
fi

[[ -z "$selection" ]] && exit 0

zsb_open ${ZSB_CHARM_LINKS_DICTIONARY[$selection]}

exit 0

# You must declare `ZSB_CHARM_LINKS_DICTIONARY` variable in ~/.zshenv
#
# example
#
# declare -Ar ZSB_CHARM_LINKS_DICTIONARY=(
#   [google]='https://www.google.com'
#   [runescape]='https://www.runescape.com'
# )
#
