#!/usr/bin/env zsh
set -o errexit
set -o nounset
set -o pipefail

declare files=$(ls ${ZSB_CHARM_ROOT_WORKSPACE})

declare dirs
for file in ${(z)files}; do
  [[ -d ${ZSB_CHARM_ROOT_WORKSPACE}/${file} ]] && \
    dirs+="$file\n"
done

declare selection=$(echo "$dirs" | rofi ${(z)commonRofiProps} -i -p "Open")

[[ -z "$selection" ]] && exit 0

code ${ZSB_CHARM_ROOT_WORKSPACE}/${selection}

exit 0

# You must declare `ZSB_CHARM_ROOT_WORKSPACE` variable in ~/.zshenv
#
# example
#
# declare ZSB_CHARM_ROOT_WORKSPACE=~/projects
#
