#!/usr/bin/env zsh
set -euo pipefail

# (tightly coupled with tmux config and nvim)
# for tmux conf, see https://github.com/EdgardoArriagada/dotFiles/blob/main/tmux/home/.tmux.conf

local selection=`< /dev/stdin`

if [[ -n "$selection" ]]; then
  zsb_clipcopy "$selection"
  exit 0
fi

handle_input() {
  case $1 in
    w|e) tmux send -X select-word \; send -X other-end \; send -X copy-selection ;;
    y) tmux send -X copy-line ;;
    b) tmux send -X begin-selection \; send -X previous-word \; send -X copy-selection ;;
    $) tmux send -X copy-end-of-line ;;
    q) exit ;;
    *) exit 1 ;;
  esac
}

tmux command-prompt -1 -p '(w/e/b/y/$/q)' "run-shell '$(declare -f handle_input); handle_input \"%%\"'"
