#!/usr/bin/env zsh
set -o errexit
set -o pipefail

local -r lastPomodoroSessionLines="$(tmux capture-pane -p -t pomodoro | sed '/^$/d' | tail -1)"

local popupMessage
local popupWidth

if [[ "$lastPomodoroSessionLines" =~ "^⏳" ]]; then
  popupMessage="$lastPomodoroSessionLines"
  popupWidth=9
else
  popupMessage=" No pomodoro timer is running."
  popupWidth=33
fi

if (( $ZSB_MACOS )); then
  osascript -e "display notification \"$popupMessage\""
else
  timeout 0.6 \
    rofi -width "-${popupWidth}" -e "$popupMessage"
fi

exit 0
