#!/usr/bin/env zsh
set -euo pipefail

local paneId=${1:?paneId required}
local workingDir=${2:?working directory required}
local width=$(tmux display-message -p -t "$paneId" '#{window_width}')
local windowSize=$(tmux show-window-options -v -t "$paneId" window-size)
local sessionId=

if tmux resize-window -t "$paneId" -x 320; then
  sessionId=$(tmux capture-pane -pt "$paneId" -J | tail -n 2 | rg -o -m 1 --replace '$1' ' · ([0-9a-fA-F]{8}(-[0-9a-fA-F]{4}){3}-[0-9a-fA-F]{12}) · ' || true)
  tmux resize-window -t "$paneId" -x "$width"
  if [[ -n $windowSize ]]; then
    tmux set-window-option -t "$paneId" window-size "$windowSize"
  else
    tmux set-window-option -u -t "$paneId" window-size
  fi
fi

if [[ ! $sessionId =~ '^[0-9a-fA-F]{8}(-[0-9a-fA-F]{4}){3}-[0-9a-fA-F]{12}$' ]]; then
  tmux display-message 'No Codex session found in this pane'
  exit 0
fi

tmux new-window -n 'codex ' -c "$workingDir" "codex fork $sessionId"
