#!/usr/bin/env zsh
set -o errexit
set -o pipefail

# (tightly coupled with tmux config, ripgrep, and nvim)
# for tmux conf, see https://github.com/EdgardoArriagada/dotFiles/blob/main/tmux/home/.tmux.conf

local lines=( ${(s.§.)"${@}"} )
local fileName=${lines[1]}

if [[ ! -f ${fileName} ]]
  then exit 1
fi

local cursorLine=${lines[${#lines}]}

function loadFile() {
  # cargo
  export PATH=$PATH:~/.cargo/bin
  # fnm
  eval "$(fnm env --use-on-cd)"

  case $# in
    1) nvim ${1} ;;
    2) nvim ${1} +${2} ;;
  esac
}

case ${#lines} in
  1) loadFile ${fileName} ;;
  *)
    # get number out of first number until ':' in a line using param expansion
    local lineNumber=${cursorLine%%:*}

    loadFile ${fileName} ${lineNumber}
    ;;
esac

exit 0
