#!/usr/bin/env zsh
# set -o errexit
# set -o pipefail
set -o nounset

# (tightly coupled with tmux config and nvim)
# for tmux conf, see https://github.com/EdgardoArriagada/dotFiles/blob/main/tmux/home/.tmux.conf

local selection=`< /dev/stdin`

if [[ -n "$selection" ]]; then
  zsb_clipcopy <<< "$selection"
  exit 0
fi

local fn='inline_fn() {
  case $1 in
    "w") tmux send -X select-word \; send -X other-end \; send -X copy-selection ;;
    "y") tmux send -X copy-line ;;
    "$") tmux send -X copy-end-of-line ;;
    "q") exit 0 ;;
    *) exit 1 ;;
  esac
}'

tmux command-prompt -1 -p "(w/y/$/q)" "run-shell '$fn; inline_fn \"%%\"'"

exit 0
