#!/usr/bin/env zsh
set -o errexit
set -o pipefail

local result=`pdoro -r 2>&1` # capture both stdout and stderr

local popupMessage
local popupWidth
local prefix

if [[ "$result" =~ '^[0-9]' ]]; then
  popupWidth=9
  result="⌛ ${result}"

  else popupWidth=33
fi

if (( $ZSB_MACOS ))
  then alert $result
  else timeout 0.6 rofi -width -${popupWidth} -e $result
fi

exit 0
