#!/usr/bin/env zsh
set -o errexit
set -o pipefail

if (( $ZSB_MACOS )); then
  declare -r selection=$(print -l "${(@k)ZSB_CHARM_LINKS_DICTIONARY}" | choose)
else
  declare -r selection=$(print -l "${(@k)ZSB_CHARM_LINKS_DICTIONARY}" | rofi ${(z)commonRofiProps} -i -p "Open link")
fi

[[ -z "$selection" ]] && exit 0

zsb_open "${ZSB_CHARM_LINKS_DICTIONARY[$selection]}"

exit 0

# You must declare `ZSB_CHARM_LINKS_DICTIONARY` variable in ~/.zshenv
#
# example
#
# declare -Ar ZSB_CHARM_LINKS_DICTIONARY=(
#   [google]='https://www.google.com'
#   [runescape]='https://www.runescape.com'
# )
#
