### GLOBAL VARIABLES ###

# Colors
# usefull link: https://misc.flogisoft.com/bash/tip_colors_and_formatting

ZSB_FOREGROUND="\e[38;5;"

ZSB_COLOR_FOREGROUND_RED="${ZSB_FOREGROUND}9m"
ZSB_COLOR_FOREGROUND_GREEN="${ZSB_FOREGROUND}10m"
ZSB_COLOR_FOREGROUND_YELLOW="${ZSB_FOREGROUND}11m"
ZSB_COLOR_FOREGROUND_BLUE="${ZSB_FOREGROUND}12m"
ZSB_COLOR_FOREGROUND_PURPLE="${ZSB_FOREGROUND}13m"

ZSB_LIGHT_GRAY="\e[37m"

ZSB_NO_COLOR="\033[0m"

# start highlighting and end highlighting variables
ZSB_SHL="$ZSB_COLOR_FOREGROUND_YELLOW"
ZSB_EHL="$ZSB_NO_COLOR"

# MESSAGE LABELS

ZSB_LABEL="${ZSB_LIGHT_GRAY}zsb${ZSB_NO_COLOR}"

ZSB_ERROR="${ZSB_LABEL} ${ZSB_COLOR_FOREGROUND_RED}ERROR${ZSB_NO_COLOR}:"
ZSB_SUCCESS="${ZSB_LABEL} ${ZSB_COLOR_FOREGROUND_GREEN}SUCCESS${ZSB_NO_COLOR}:"
ZSB_WARNING="${ZSB_LABEL} ${ZSB_COLOR_FOREGROUND_YELLOW}WARNING${ZSB_NO_COLOR}:"
ZSB_INFO="${ZSB_LABEL} ${ZSB_COLOR_FOREGROUND_BLUE}INFO${ZSB_NO_COLOR}:"
ZSB_PROMPT="${ZSB_LABEL} ${ZSB_COLOR_FOREGROUND_PURPLE}PROMPT${ZSB_NO_COLOR}:"

ZSB_EXPECTED=" ${ZSB_COLOR_FOREGROUND_GREEN}+ Expected${ZSB_NO_COLOR}:"
ZSB_CURRENT=" ${ZSB_COLOR_FOREGROUND_RED}- Current${ZSB_NO_COLOR}:"

# we create functions instead of subshells (for clear global namespace)
# because we need to source files in this current shell

# Git
ZSB_GIT_DEFAULT_BRANCHES="(master|develop|devel|dev|main)"
ZSB_GIT_AWARE="'--aware:Proceed even if affecting a default branch'"
ZSB_GIT_FORCE="'--force:Proceed even in commit have already been pushed online'"

